require("vain.layout.termfair")
require("vain.layout.browse")
require("vain.layout.cascadebrowse")
require("vain.layout.uselessfair")
require("vain.layout.gimp")
require("vain.layout.cascade")
require("vain.layout.centerwork")
module("vain.layout")
